/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Spark2dpl */

#ifndef _Included_Spark2dpl
#define _Included_Spark2dpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Spark2dpl
 * Method:    load
 * Signature: (Lscala/collection/Iterator;Lorg/apache/spark/sql/types/StructType;Ljava/util/Properties;Lorg/apache/log4j/Logger;)Z
 */
JNIEXPORT jboolean JNICALL Java_Spark2dpl_load
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
